name: chat_gpt_api
description: Chat GPT wrapper for flutter apps witten in dart language. Initial release supports Text Completion, Code Completion and Image Generation
version: 1.0.1
homepage: https://github.com/leo-elstin/chat_gpt

environment:
  sdk: ^3.0.0

dependencies:
  dio: ^5.0.0


dev_dependencies:
  test: ^1.0.0
  lints: ^2.0.0
